### ISSUE TITLE
missing com/sun/media/imageio/stream/StreamSegmentMapper on dec

### ISSUE THREAD

**Issue by walterwang** [johnperry/DicomAnonymizerTool#2]
When using the -dec option, I get a missing imageio jar library on linux
```

Exception in thread "pool-1-thread-6" java.lang.NoClassDefFoundError: com/sun/media/imageio/stream/StreamSegmentMapper
        at org.dcm4cheri.imageio.plugins.DcmImageReaderSpi.createReaderInstance(DcmImageReaderSpi.java:124)
        at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
        at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMDecompressor.decompress(DICOMDecompressor.java:198)
        at org.rsna.dicomanonymizertool.DicomAnonymizerTool$Processor.run(DicomAnonymizerTool.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageio.stream.StreamSegmentMapper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

```

**Comment by jmesterh** [comment]
You need to install the Native JAI ImageIO libraries. There is a good tutorial [here](https://geoserver.geo-solutions.it/edu/en/install_run/jai_io_install.html).

**Comment by johnperry** [comment]
Walter:

The SegmentStreamMapper is part of the ImageIO Tools. The ImageIO Tools are not included in the DicomAnonymizerTool, so you will have to install them. How to do that depends on what platform you are running on and what version of Java you are running. If you tell me those two things, I might be able to help.

JP

From: WalterWang 
Sent: Thursday, November 08, 2018 3:57 PM
To: johnperry/DicomAnonymizerTool 
Cc: Subscribed 
Subject: [johnperry/DicomAnonymizerTool] missing com/sun/media/imageio/stream/StreamSegmentMapper on dec (#2)

When using the -dec option, I get a missing imageio jar library


Exception in thread "pool-1-thread-6" java.lang.NoClassDefFoundError: com/sun/media/imageio/stream/StreamSegmentMapper
        at org.dcm4cheri.imageio.plugins.DcmImageReaderSpi.createReaderInstance(DcmImageReaderSpi.java:124)
        at javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
        at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
        at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMDecompressor.decompress(DICOMDecompressor.java:198)
        at org.rsna.dicomanonymizertool.DicomAnonymizerTool$Processor.run(DicomAnonymizerTool.java:394)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.media.imageio.stream.StreamSegmentMapper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by walterwang** [comment]
following the tutorial worked, thank you!

**Comment by walterwang** [comment]
rebuilding from the ant projects appears to work
