### ISSUE TITLE
java out of heap memory

### ISSUE THREAD

**Issue by walterwang** [johnperry/DicomAnonymizerTool#3]
Getting a strange out of heap memory issue. CPU usage suddenly jumps from 30% to 90-99% and remains there. The anonymizer gets stuck a long time on a certain dicom file, then gives this error. 

After a while, a different thread begins. pool-1-thread-2 in this case, and continues anonymizing, but becomes much much slower. 
Not sure if its relevant, but I also get a 12:02:15 WARN  [DICOMAnonymizer] Unable to delete ... log for every file to be anonymized. 

> Thread: pool-1-thread-1: Anonymizing /body/974.dcm
>    Anonymized file: body/974.dcm
> Exception in thread "main" Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space
> 	at java.lang.Class.getDeclaredFields0(Native Method)
> 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
> 	at java.lang.Class.getField0(Class.java:2975)
> 	at java.lang.Class.getField(Class.java:1701)
> 	at org.dcm4che.dict.Tags.forName(Tags.java:73)
> 	at org.rsna.ctp.objects.DicomObject.getElementTag(DicomObject.java:1057)
> 	at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.getElementTag(DICOMAnonymizerContext.java:446)
> 	at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.getElementTag(DICOMAnonymizerContext.java:413)
> 	at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.<init>(DICOMAnonymizerContext.java:107)
> 	at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizer.anonymize(DICOMAnonymizer.java:155)
> 	at org.rsna.dicomanonymizertool.DicomAnonymizerTool$Processor.run(DicomAnonymizerTool.java:436)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> java.lang.OutOfMemoryError: Java heap space
> 	at java.io.UnixFileSystem.resolve(UnixFileSystem.java:108)
> 	at java.io.File.<init>(File.java:367)
> 	at org.rsna.dicomanonymizertool.DicomAnonymizerTool.anonymize(DicomAnonymizerTool.java:315)
> 	at org.rsna.dicomanonymizertool.DicomAnonymizerTool.anonymize(DicomAnonymizerTool.java:312)
> 	at org.rsna.dicomanonymizertool.DicomAnonymizerTool.go(DicomAnonymizerTool.java:298)
> 	at org.rsna.dicomanonymizertool.DicomAnonymizerTool.main(DicomAnonymizerTool.java:223)
>

**Comment by johnperry** [comment]
Walter:

What heap size have you specified for the DicomAnonymizerTool?

Is there anything special about the images that cause the problem?

What is the modality?

Can you send me an image that demonstrates the problem? (johnperry@dls.net)

JP

From: WalterWang 
Sent: Tuesday, May 07, 2019 11:04 AM
To: johnperry/DicomAnonymizerTool 
Cc: Subscribed 
Subject: [johnperry/DicomAnonymizerTool] java out of heap memory (#3)

Getting a strange out of heap memory issue. CPU usage suddenly jumps from 30% to 90-99% and remains there. The anonymizer gets stuck a long time on a certain dicom file, then gives this error.

After a while, a different thread begins. pool-1-thread-2 in this case, and continues anonymizing, but becomes much much slower.
Not sure if its relevant, but I also get a 12:02:15 WARN [DICOMAnonymizer] Unable to delete ... log for every file to be anonymized.

  Thread: pool-1-thread-1: Anonymizing /body/974.dcm
  Anonymized file: body/974.dcm
  Exception in thread "main" Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space
  at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
  at java.lang.Class.getField0(Class.java:2975)
  at java.lang.Class.getField(Class.java:1701)
  at org.dcm4che.dict.Tags.forName(Tags.java:73)
  at org.rsna.ctp.objects.DicomObject.getElementTag(DicomObject.java:1057)
  at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.getElementTag(DICOMAnonymizerContext.java:446)
  at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.getElementTag(DICOMAnonymizerContext.java:413)
  at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizerContext.(DICOMAnonymizerContext.java:107)
  at org.rsna.ctp.stdstages.anonymizer.dicom.DICOMAnonymizer.anonymize(DICOMAnonymizer.java:155)
  at org.rsna.dicomanonymizertool.DicomAnonymizerTool$Processor.run(DicomAnonymizerTool.java:436)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
  java.lang.OutOfMemoryError: Java heap space
  at java.io.UnixFileSystem.resolve(UnixFileSystem.java:108)
  at java.io.File.(File.java:367)
  at org.rsna.dicomanonymizertool.DicomAnonymizerTool.anonymize(DicomAnonymizerTool.java:315)
  at org.rsna.dicomanonymizertool.DicomAnonymizerTool.anonymize(DicomAnonymizerTool.java:312)
  at org.rsna.dicomanonymizertool.DicomAnonymizerTool.go(DicomAnonymizerTool.java:298)
  at org.rsna.dicomanonymizertool.DicomAnonymizerTool.main(DicomAnonymizerTool.java:223)

**Comment by walterwang** [comment]
These images are mri of abdomens with around 12k studies 1000-1500 dicoms per studies. It doesn't get stuck on any particular mri's, but the drives are mounted by sshfs, the issue was resolved when I did the anonymization without sshfs.
